// packages/vue/src/components/switch-language/index.vue
<script lang="ts" setup>
// locale
const { t, locale, locales } = useI18n()
const router = useRouter()
const switchLocalePath = useSwitchLocalePath()
const { MIX_BASE_URL, MIX_ASSETS_URL } = useRuntimeConfig()

// icon
const iconMap = new Map([
  ['en', `${MIX_ASSETS_URL}/lang/en-US.png`],
  ['zh', `${MIX_ASSETS_URL}/lang/zh-CHT.png`],
])
const icon = computed(() => iconMap.get(locale.value) || '')

// dropdown status
const show = ref(false)

/**
 * @desc on select locale
 */
const onSelectLocale = (locale: string) => {
  location.href = `${MIX_BASE_URL}/vue${switchLocalePath(locale)}`
}
</script>

<template>
  <div
    class="flex items-center justify-center cursor-pointer relative select-none"
    @keyup="() => false"
    @click="show = !show"
  >
    <!--current locale-->
    <img :src="icon" alt="" class="w-8 lg:w-9 h-8 lg:h-9" />
    <!--mask-->
    <button v-if="show" class="fixed left-0 top-0 w-full h-full z-0" @click.prevent.stop="show = false" />
    <!--dropdown-->
    <transition name="fade">
      <div v-show="show" class="absolute top-0 left-1/2 -translate-x-1/2 pt-12 md:pt-11 lg:pt-12 z-10 w-12">
        <div class="bg-white rounded-1.5 py-1 shadow-md">
          <!--locale list-->
          <button
            @click.prevent.stop="onSelectLocale(item)"
            v-for="item in locales"
            :key="item"
            class="hover:bg-gray-200 transition-colors p-1.5"
          >
            <img :src="iconMap.get(item)" alt="" class="w-9 h-9" />
          </button>
        </div>
      </div>
    </transition>
  </div>
</template>

// projects/svelte-kit2/src/components/header/components/switch-language/index.svelte
<script lang="ts">
  import { fade } from 'svelte/transition'
  import { locales, locale } from '$lib/i18n'
  import { goto } from '$app/navigation'
  import { MIX_ASSETS_URL } from '$env/static/public'

  let clazz = ''
  export { clazz as class }

  // icon
  const iconMap = new Map([
    ['en', `${MIX_ASSETS_URL}/lang/en-US.png`],
    ['zh', `${MIX_ASSETS_URL}/lang/zh-CHT.png`],
  ])
  let icon
  $: {
    icon = iconMap.get($locale)
  }

  // on switch language
  const onSelectLocale = (l: string) => {
    goto(location?.pathname?.replace(`/${locale.get()}/`, `/${String(l)}/`))
    show = false
  }

  // dropdown status
  let show = false

  // dropdown fade
  const dropdownTransition = { duration: 300 }
</script>

<div class={`${clazz} flex items-center justify-center cursor-pointer relative select-none`} tabindex="0" role="button" on:click={() => (show = !show)} on:keyup={() => false}>
  <!--current locale-->
  <img src={icon} alt="" class="w-8 lg:w-9 h-8 lg:h-9" />

  {#if show}
    <!--mask-->
    <button class="fixed left-0 top-0 w-full h-full z-0" on:click|preventDefault|stopPropagation={() => (show = false)} />
    <!--dropdown-->
    <div class="absolute top-0 left-1/2 -translate-x-1/2 pt-12 md:pt-11 lg:pt-12 z-10 w-12" transition:fade={dropdownTransition}>
      <div class="bg-white rounded-1.5 py-1 shadow-md">
        {#each $locales as item, i}
          <button on:click|preventDefault|stopPropagation={() => onSelectLocale(item)} class="over:bg-gray-200 transition-colors p-1.5">
            <img src={iconMap.get(item) || ''} alt="" class="w-9 h-9" />
          </button>
        {/each}
      </div>
    </div>
  {/if}
</div>
