// projects/next14/src/components/home/index.tsx
'use client'
import type { ElementPositionProgress } from '@about-me-mix/communal/store/section-progress'
import { useRef, useEffect } from 'react'
import { setSectionProgress } from './store/progress'
import { getChildrenRect, getElementProgressData } from '@about-me-mix/communal/store/section-progress'
import SectionOpening from './components/opening'
import SectionDialogue from './components/dialogue'
import SectionExperience from './components/experience'
import SectionCoding from './components/coding'
import SectionShader from './components/shader'
import { useClientStore } from '@/stores/initialize'

/**
 * @desc 首頁
 */
export default function Home() {
  /**
   * @desc Cache Section Position
   */
  const childrenProgressData = useRef<ElementPositionProgress[]>([])
  const onScrollHandler = () => setSectionProgress(getElementProgressData(childrenProgressData.current))
  useEffect(() => {
    window.addEventListener('scroll', onScrollHandler)
    return () => {
      window.removeEventListener('scroll', onScrollHandler)
    }
  }, [])

  /**
   * @desc Cache Scroll Data
   */
  const sizeUpdateTimestamp = useClientStore(state => state.sizeUpdateTimestamp)
  const main = useRef<HTMLElement>(null)
  useEffect(() => {
    if (!main.current) return
    childrenProgressData.current = getChildrenRect(main.current)
    onScrollHandler()
  }, [main, sizeUpdateTimestamp])

  // Component Child
  const section = [SectionOpening, SectionDialogue, SectionExperience, SectionCoding, SectionShader]

  return (
    <main ref={main}>
      {section.map((Component, index) => (
        <Component key={index} index={index} />
      ))}
    </main>
  )
}

// projects/svelte-kit4/src/components/home/index.svelte
<script lang="ts">
  import { type ElementPositionProgress, getChildrenRect, getElementProgressData } from '@about-me-mix/communal/store/section-progress'
  import { state } from '../../stores/initialize'
  import { setSectionProgress } from './store/section-progress'
  import { onDestroy, onMount } from 'svelte'
  import { browser } from '$app/environment'

  /**
   * @desc Cache Section Position
   */
  let childrenProgressData: ElementPositionProgress[] = []
  const onScrollHandler = () => setSectionProgress(getElementProgressData(childrenProgressData))
  onMount(() => browser && window.addEventListener('scroll', onScrollHandler))
  onDestroy(() => browser && window.removeEventListener('scroll', onScrollHandler))

  /**
   * @desc Cache Scroll Data
   */
  let main: HTMLElement
  const initialize = async () => {
    await new Promise(requestAnimationFrame)
    childrenProgressData = getChildrenRect(main)
    onScrollHandler()
  }
  const action = dom => (main = dom)
  $: if (main && $state.sizeUpdateTimestamp) initialize()

  // Component Child
  import Opening from './components/opening/index.svelte'
  import Dialogue from './components/dialogue/index.svelte'
  import Experience from './components/experience/index.svelte'
  import Coding from './components/coding/index.svelte'
  import Shader from './components/shader/index.svelte'
  const section = [Opening, Dialogue, Experience, Coding, Shader]
</script>

<!--Home Page-->
<main use:action>
  {#each section as Component, index (index)}
    <svelte:component this={Component} {index} />
  {/each}
</main>
