// packages/vue/src/components/section/experience/component/point.vue
<script lang="ts" setup>
import { Work } from '@about-me-mix/common/gsap-experience'

defineProps({
  details: Object as PropType<Work>,
})
</script>

<template>
  <div
    :data-group="details.group"
    :class="{ 'ml-24 -mt-20 text-6 pr-3': details.category, 'text-5': !details.category }"
    class="work flex items-start text-white relative"
  >
    <!--left line-->
    <div v-if="!details.category" class="work__line relative w-6 h-0 border-t-4 mt-5" />

    <div class="flex-1">
      <!--name-->
      <div class="work__head mb-3 flex items-center rounded-1.5">
        <!--date  -->
        <div v-if="details.date" class="work__head-date inline-block bg-white px-3 py-1.5 rounded-l-1.5 font-bold">
          {{ details.date }}
        </div>
        <!--title-->
        <h1 v-t="details.label" class="inline-block text-white px-3 py-1.5" />
      </div>

      <!--team-->
      <div v-if="'end' in details || 'team' in details" class="pl-4 leading-0 whitespace-nowrap mb-3">
        <span
          class="work__end leading-4 inline-block text-4 m-0 px-2 py-1.5 rounded-l"
          :data-color="details.end"
          v-t="`end[${details.end}]`"
        />
        <span
          class="work__team leading-4 inline-block text-4 m-0 px-2 py-1.5 bg-white rounded-r"
          :data-color="details.team"
          v-t="`team[${details.team}]`"
        />
      </div>

      <!--technology-->
      <div v-if="details.technology?.length" class="pl-8 max-w-70 flex flex-wrap">
        <span
          v-for="item in details.technology"
          :key="item"
          class="work__tag text-3.5 text-bold px-2 py-0.5 rounded mr-2 mb-2"
        >
          {{ item }}
        </span>
      </div>
    </div>

    <!--right line-->
    <div v-if="details.count" class="work__line relative w-6 h-16.5 rounded-rt-2 border-t-4 border-r-4 mt-5.5">
      <span
        class="work__line-end w-4 h-4 border-l-4 border-b-4 inline-block absolute -right-4 -bottom-4 rounded-lb-2"
      />
    </div>
  </div>
</template>

<style lang="scss" scoped>
@import '@about-me-mix/common/gsap-experience';
</style>

// packages/react/src/components/section/experience/component/point.tsx
import type { Work } from '@about-me-mix/common/gsap-experience'
import '@about-me-mix/common/gsap-experience.scss'
import { useTranslation } from 'next-i18next'

/**
 * @desc Work Point
 */
export default ({ details }: { details: Work }) => {
  const { t } = useTranslation()

  return (
    <div
      data-group={details.group}
      className={`work flex items-start text-white relative ${
        details.category ? 'ml-24 -mt-20 text-6 pr-3' : 'text-5'
      }`}
    >
      {/*left line*/}
      {!details.category && <div className="work__line relative w-6 h-0 border-t-4 mt-5" />}

      <div className="flex-1">
        {/*name*/}
        <div className="work__head mb-3 flex items-center rounded-1.5">
          {/*date*/}
          {details.date && (
            <div className="work__head-date inline-block bg-white px-3 py-1.5 rounded-l-1.5 font-bold">
              {details.date}
            </div>
          )}
          {/*title*/}
          <h1 className="inline-block text-white px-3 py-1.5">{t(details.label!)}</h1>
        </div>

        {/*team*/}
        {('end' in details || 'team' in details) && (
          <div className="pl-4 leading-0 whitespace-nowrap mb-3">
            <span
              className="work__end leading-4 inline-block text-4 m-0 px-2 py-1.5 rounded-l"
              data-color={details.end}
            >
              {t(`end.${details.end}`)}
            </span>
            <span
              className="work__team leading-4 inline-block text-4 m-0 px-2 py-1.5 bg-white rounded-r"
              data-color={details.team}
            >
              {t(`team.${details.team}`)}
            </span>
          </div>
        )}

        {/*technology*/}
        {details.technology?.length && (
          <div className="pl-8 max-w-70 flex flex-wrap">
            {details.technology.map(item => (
              <span key={item} className="work__tag text-3.5 text-bold px-2 py-0.5 rounded mr-2 mb-2">
                {item}
              </span>
            ))}
          </div>
        )}
      </div>

      {/*right line*/}
      {!!details.count && (
        <div className="work__line relative w-6 h-16.5 rounded-rt-2 border-t-4 border-r-4 mt-5.5">
          <span className="work__line-end w-4 h-4 border-l-4 border-b-4 inline-block absolute -right-4 -bottom-4 rounded-lb-2" />
        </div>
      )}
    </div>
  )
}
