// packages/vue/src/components/switch-language/index.vue
<script lang="ts" setup>
import enUS from '@about-me-mix/common/assets/en-US.png?url'
import zhCHT from '@about-me-mix/common/assets/zh-CHT.png?url'

// locale
const { t, locale, locales, setLocale } = useI18n()

// icon
const iconMap = new Map([
  ['en', enUS],
  ['zh', zhCHT],
])
const icon = computed(() => iconMap.get(locale.value) || '')

// dropdown status
const show = ref(false)

/**
 * @desc on select locale
 */
const onSelectLocale = (locale: string) => {
  show.value = false
  setLocale(locale)
}
</script>

<template>
  <div class="h-full flex items-center cursor-pointer relative select-none" @click="show = true">
    <!--current locale-->
    <img :src="icon" alt="" class="w-24px h-24px mx-6px" />
    <!--mask-->
    <div v-if="show" class="fixed left-0 top-0 w-full h-full z-0" @click.prevent.stop="show = false" />
    <!--dropdown-->
    <transition name="fade">
      <div v-show="show" class="absolute top-0 right-0 pt-46px z-10">
        <div class="bg-white rounded-6px py-4px shadow-md">
          <!--locale list-->
          <div
            @click.prevent.stop="onSelectLocale(item)"
            v-for="item in locales"
            :key="item"
            class="hover:bg-gray-200 transition-colors p-6px"
          >
            <img :src="iconMap.get(item)" alt="" class="w-24px h-24px" />
          </div>
        </div>
      </div>
    </transition>
  </div>
</template>

<style lang="scss">
.fade {
  &-enter-active,
  &-leave-active {
    transition: opacity 0.3s;
  }
  &-enter-from,
  &-leave-to {
    opacity: 0;
  }
}
</style>

// packages/svelte/src/components/switch-language/index.svelte
<script lang="ts">
  import { fade } from 'svelte/transition'
  import { locales, locale } from '@/core/i18n'
  import { goto } from '$app/navigation'
  import enUS from '@about-me-mix/common/assets/en-US.png?url'
  import zhCHT from '@about-me-mix/common/assets/zh-CHT.png?url'

  // icon
  const iconMap = new Map([
    ['en', enUS],
    ['zh', zhCHT],
  ])
  let icon = iconMap.get($locale)

  // on switch language
  const onSelectLocale = (l: string) => {
    goto(location?.pathname?.replace(`/${locale.get()}/`, `/${String(l)}/`))
    show = false
  }

  // dropdown status
  let show = false

  // dropdown fade
  const dropdownTransition = { duration: 300 }
</script>

<div class="h-full flex items-center cursor-pointer relative select-none" on:click={() => (show = true)}>
  <!--current locale-->
  <img src={icon} alt="" class="w-24px h-24px mx-6px" />

  {#if show}
    <!--mask-->
    <div
      v-if="show"
      class="fixed left-0 top-0 w-full h-full z-0"
      on:click|preventDefault|stopPropagation={() => (show = false)}
    />
    <!--dropdown-->
    <div class="absolute top-0 right-0 pt-46px z-10" transition:fade={dropdownTransition}>
      <div class="bg-white rounded-6px py-4px shadow-md">
        {#each $locales as item, i}
          <div
            on:click|preventDefault|stopPropagation={() => onSelectLocale(item)}
            :key="item"
            class="hover:bg-gray-200 transition-colors p-6px"
          >
            <img src={iconMap.get(item) || ''} alt="" class="w-24px h-24px" />
          </div>
        {/each}
      </div>
    </div>
  {/if}
</div>
