// projects/next14/src/components/home/index.tsx
'use client'
import type { ElementPositionProgress } from '@about-me-mix/communal/store/section-progress'
import { useRef, useEffect } from 'react'
import { setSectionProgress } from './store/progress'
import { getChildrenRect, getElementProgressData } from '@about-me-mix/communal/store/section-progress'
import SectionOpening from './components/opening'
import SectionDialogue from './components/dialogue'
import SectionExperience from './components/experience'
import SectionCoding from './components/coding'
import SectionShader from './components/shader'
import { useClientStore } from '@/stores/initialize'

/**
 * @desc 首頁
 */
export default function Home() {
  /**
   * @desc Cache Section Position
   */
  const childrenProgressData = useRef<ElementPositionProgress[]>([])
  const onScrollHandler = () => setSectionProgress(getElementProgressData(childrenProgressData.current))
  useEffect(() => {
    window.addEventListener('scroll', onScrollHandler)
    return () => {
      window.removeEventListener('scroll', onScrollHandler)
    }
  }, [])

  /**
   * @desc Cache Scroll Data
   */
  const sizeUpdateTimestamp = useClientStore(state => state.sizeUpdateTimestamp)
  const main = useRef<HTMLElement>(null)
  useEffect(() => {
    if (!main.current) return
    childrenProgressData.current = getChildrenRect(main.current)
    onScrollHandler()
  }, [main, sizeUpdateTimestamp])

  // Component Child
  const section = [SectionOpening, SectionDialogue, SectionExperience, SectionCoding, SectionShader]

  return (
    <main ref={main}>
      {section.map((Component, index) => (
        <Component key={index} index={index} />
      ))}
    </main>
  )
}

// projects/nuxt3/src/components/home/index.vue
<script setup lang="ts">
import { type ElementPositionProgress, getChildrenRect, getElementProgressData } from '@about-me-mix/communal/store/section-progress'
import { useSectionProgress } from '~/components/home/store/section-progress'
import { useClientStore } from '~/store/initialize'

/**
 * @desc Cache Section Position
 */
const childrenProgressData = ref<ElementPositionProgress[]>([])
const onScrollHandler = () => useSectionProgress().setSectionProgress(getElementProgressData(childrenProgressData.value))
onBeforeMount(() => window.addEventListener('scroll', onScrollHandler))
onUnmounted(() => window.removeEventListener('scroll', onScrollHandler))

/**
 * @desc Cache Scroll Data
 */
const main = ref<HTMLElement>()
const sizeUpdateTimestamp = computed(() => useClientStore().sizeUpdateTimestamp) // on resize
watch([main, sizeUpdateTimestamp], () => {
  if (!main.value) return
  childrenProgressData.value = getChildrenRect(main.value)
  onScrollHandler()
})

// Component Child
import Opening from './components/opening'
import Dialogue from './components/dialogue'
import Experience from './components/experience'
import Coding from './components/coding'
import Shader from './components/shader'
const section = [Opening, Dialogue, Experience, Coding, Shader]
</script>

<template>
  <main ref="main">
    <Component v-for="(component, index) in section" :is="component" :key="index" :index="index" />
  </main>
</template>
