// packages/svelte/src/components/layout/index.svelte
<script lang="ts">
  import { LAYOUT } from '@about-me-mix/common/constant'
  import { page } from '$app/stores'
  import Default from '@/layouts/default.svelte'
  import Single from '@/layouts/single.svelte'
</script>

<svelte:component this={$page.data.layout === LAYOUT.SINGLE ? Single : Default}>
  <slot />
</svelte:component>

// packages/react/src/components/layout/index.tsx
import { LAYOUT } from '@about-me-mix/common/constant'
import LayoutSingle from '@/layouts/single'
import LayoutDefault from '@/layouts/default'
import React from 'react'

/**
 * @desc 自動判斷 layout
 */
export default ({ layout, children }: { layout: number; children: React.ReactNode }) => {
  const Layout = layout === LAYOUT.SINGLE ? LayoutSingle : LayoutDefault
  return <Layout>{children}</Layout>
}
