// projects/svelte-kit4/src/layouts/index.svelte
<script lang="ts">
  import { LAYOUTS } from '@about-me-mix/communal/src/constant'
  import { page } from '$app/stores'
  import Default from '@/layouts/default.svelte'
  import Normal from '@/layouts/normal.svelte'
</script>

<svelte:component this={$page.data.layout === LAYOUTS.NORMAL ? Normal : Default}>
  <slot />
</svelte:component>

// projects/next14/src/layouts/index.tsx
import { LAYOUTS } from '@about-me-mix/communal/src/constant'
import Normal from '@/layouts/normal'
import Default from '@/layouts/default'
import React from 'react'

/**
 * @desc 自動判斷 layout
 */
export default ({ layout, children }: { layout: string; children: React.ReactNode }) => {
  const Layout = layout === LAYOUTS.NORMAL ? Normal : Default
  return <Layout>{children}</Layout>
}
