// projects/next14/src/components/home/components/shader/index.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { useTranslation } from 'next-i18next'
import { createShaderTween, type TweenShader } from '@about-me-mix/communal/src/shader'
import useProgress from '../../hook/use-progress'
import { useClientStore } from '@/stores/initialize'

/**
 * @desc Home WebGL
 */
export default ({ index = 0 }: { index?: number } = {}) => {
  const { t } = useTranslation()

  // tween shader
  const [shader, setShader] = useState<TweenShader>()
  useEffect(() => {
    // 嚴格模式導致需要手動初始化
    shader?.resetSize(position?.progress)
    return () => {
      shader?.kill()
    }
  }, [shader])

  // box
  const container = useRef<HTMLDivElement>(null)
  useEffect(() => {
    const canvas = container.current?.querySelector('canvas')
    if (!canvas) return
    let destroyed = false
    createShaderTween(
      canvas,
      {
        bg: '#27272a',
        bg2: '#61dafb',
        noise: `${process.env.MIX_ASSETS_URL}/noise.jpg`,
        noise2: `${process.env.MIX_ASSETS_URL}/noise2.jpg`,
      },
      false,
    ).then(tween => !destroyed && setShader(tween))
    return () => {
      destroyed = true
    }
  }, [])

  // resize
  const sizeUpdateTimestamp = useClientStore(state => state.sizeUpdateTimestamp)
  useEffect(() => {
    shader?.resetSize()
  }, [sizeUpdateTimestamp])

  // on position update
  const { position } = useProgress(index, ({ hidden, progress }) => {
    // hidden
    if (container.current) container.current.style.display = hidden ? 'none' : ''
    // update tween
    if (!hidden) shader?.progress(progress)
  })

  return useMemo(
    () => (
      <section className="h-300vh">
        <div ref={container} className="h-full">
          <canvas className="h-100vh w-full sticky top-0 z-10 pointer-events-none" />
          <div className="h-100vh" />
          <div className="w-full h-100vh relative z-0 flex items-center justify-center font-bold text-white text-10 lg:text-16">{t('thank')}</div>
        </div>
      </section>
    ),
    [t],
  )
}

// projects/svelte-kit2/src/components/home/components/shader/index.svelte
<script lang="ts">
  import { createShaderTween, type TweenShader } from '@about-me-mix/communal/src/shader'
  import { state } from '../../../../stores/initialize'
  import { t } from '$lib/i18n'
  import useProgress from '../../hook/use-progress'
  import { MIX_ASSETS_URL } from '$env/static/public'

  // progress data
  export let index = 0
  let progress = useProgress(index)

  const initialize = (container: HTMLDivElement) => {
    // update shadow params
    let shader: TweenShader

    createShaderTween(container?.querySelector('canvas'), {
      bg: '#27272a',
      bg2: '#e11d48',
      noise: `${MIX_ASSETS_URL}/noise.jpg`,
      noise2: `${MIX_ASSETS_URL}/noise2.jpg`,
    }).then(tween => {
      shader?.kill()
      shader = tween
      shader.progress($progress?.progress || 0)
    })

    // on resize
    let prevSizeUpdateTimestamp = 0
    const unSubscribe = state.subscribe(({ sizeUpdateTimestamp }) => {
      if (prevSizeUpdateTimestamp === sizeUpdateTimestamp) return
      prevSizeUpdateTimestamp = sizeUpdateTimestamp
      shader?.resetSize()
    })

    return {
      // on progress update
      update({ hidden, progress }) {
        if (hidden) return
        shader?.progress(progress)
      },
      destroy() {
        shader?.kill()
        unSubscribe()
      },
    }
  }
</script>

<section class="h-300vh">
  <div use:initialize={$progress} style:display={$progress?.hidden ? 'none' : ''} class="h-full">
    <canvas class="h-100vh w-full sticky top-0 z-10" />
    <div class="h-100vh" />
    <div class="w-full h-100vh relative z-0 flex items-center justify-center font-bold text-white text-10 lg:text-16">
      {$t('thank')}
    </div>
  </div>
</section>
