// packages/react/src/components/section/opening/component/content.tsx
import { useTranslation } from 'next-i18next'

/**
 * @desc Repeat 子層必須使用 Function Component
 */
export default ({ index }: { index: number }) => {
  const { t } = useTranslation(['common'])

  return (
    // mask
    <div key={index} className="absolute top-0 left-0 w-full h-full overflow-hidden">
      {/*box*/}
      <div
        style={index === 1 ? { backgroundImage: `url(${process.env.MIX_ASSETS_URL}/polygon-white.jpg)` } : {}}
        className={`${
          index ? `dark:brightness-75 transition-all` : ''
        } h-100vh w-full flex flex-col items-center justify-center font-medium text-4 lg:text-5 bg-center bg-cover`}
      >
        {/*icon*/}
        <svg
          className={`w-auto h-28 lg:h-40 mb-4 lg:mb-6`}
          xmlns="http://www.w3.org/2000/svg"
          viewBox="-11.5 -10.23174 23 20.46348"
        >
          <title>React Logo</title>
          <circle cx="0" cy="0" r="2.05" className={`${index ? 'fill-#61dafb' : 'fill-white dark:fill-#fefddd'}`} />
          <g className={`${index ? 'stroke-#61dafb' : 'stroke-white dark:stroke-#fefddd'}`} strokeWidth="1" fill="none">
            <ellipse rx="11" ry="4.2" />
            <ellipse rx="11" ry="4.2" transform="rotate(60)" />
            <ellipse rx="11" ry="4.2" transform="rotate(120)" />
          </g>
        </svg>
        <div className="h-36 text-center">
          {/*title*/}
          <h1 className={`text-5 lg:text-7 font-black mb-2 lg:mb-4 ${!index ? 'text-white' : 'text-black'}`}>
            {t('section.opening.title')}
          </h1>
          {/*desc*/}
          <p className={`mb-2 lg:mb-4 ${!index ? 'text-white' : 'text-gray-700'}`}>{t('section.opening.desc')}</p>
          <p className={!index ? 'text-white' : 'text-gray-700'}>{t('section.opening.target', ['Next 13'])}</p>
        </div>
      </div>
    </div>
  )
}

// projects/angular17/src/app/home/components/opening/content/content.component.ts
import { Component, Input } from '@angular/core'
import { CommonModule } from '@angular/common'
import { environment } from '../../../../../environments/environment'

@Component({
  selector: 'app-content',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './content.component.html',
  styleUrl: './content.component.scss',
})
export class ContentComponent {
  @Input() index: number = -1

  get style() {
    return this.index === 1 ? { backgroundImage: `url(${environment.MIX_ASSETS_URL}/polygon-white.jpg)` } : {}
  }
}

<!--mask-->
<div [id]="index ? 'opening-mask' : ''" class="absolute top-0 left-0 w-full h-full overflow-hidden">
  <!--box-->
  <div [ngStyle]="style" [ngClass]="{ 'dark:brightness-75 transition-all': index }" class="h-100vh w-full flex flex-col items-center justify-center font-medium text-4 lg:text-5 bg-center bg-cover">
    <!--icon-->
    <svg class="w-auto h-36 lg:h-42 mb-4 lg:mb-6" width="256px" height="271px" viewBox="0 0 256 271" version="1.1" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid">
      <title>Angular</title>
      <defs *ngIf="index === 1">
        <linearGradient x1="25.0714876%" y1="90.9292007%" x2="96.1321855%" y2="55.1837089%" id="svg_color_1">
          <stop stop-color="#E40035" offset="0%"></stop>
          <stop stop-color="#F60A48" offset="24%"></stop>
          <stop stop-color="#F20755" offset="35.2%"></stop>
          <stop stop-color="#DC087D" offset="49.4%"></stop>
          <stop stop-color="#9717E7" offset="74.5%"></stop>
          <stop stop-color="#6C00F5" offset="100%"></stop>
        </linearGradient>
        <linearGradient x1="21.8628652%" y1="12.0575311%" x2="68.3669921%" y2="68.2103006%" id="svg_color_2">
          <stop stop-color="#FF31D9" offset="0%"></stop>
          <stop stop-color="#FF5BE1" stop-opacity="0" offset="100%"></stop>
        </linearGradient>
      </defs>
      <g>
        <path
          d="M256,45.1787083 L246.756071,190.336865 L158.373321,0 L256,45.1787083 Z M194.783035,232.875768 L128.000576,270.981182 L61.2169653,232.875768 L74.7998577,199.957744 L181.200142,199.957744 L194.783035,232.875768 Z M128.000576,72.2488146 L162.994709,157.325468 L93.005291,157.325468 L128.000576,72.2488146 Z M9.14940313,190.336865 L0,45.1787083 L97.626679,0 L9.14940313,190.336865 Z"
          [attr.fill]="index === 1 ? 'url(#svg_color_1)' : '#ffffff'"
        ></path>
        <path
          d="M256,45.1787083 L246.756071,190.336865 L158.373321,0 L256,45.1787083 Z M194.783035,232.875768 L128.000576,270.981182 L61.2169653,232.875768 L74.7998577,199.957744 L181.200142,199.957744 L194.783035,232.875768 Z M128.000576,72.2488146 L162.994709,157.325468 L93.005291,157.325468 L128.000576,72.2488146 Z M9.14940313,190.336865 L0,45.1787083 L97.626679,0 L9.14940313,190.336865 Z"
          [attr.fill]="index === 1 ? 'url(#svg_color_2)' : '#ffffff'"
        ></path>
      </g>
    </svg>
    <div class="h-36 text-center">
      <!--title-->
      <h1 i18n="@@section.opening.title" [ngClass]="!index ? 'text-white' : 'text-black'" class="text-5 lg:text-7 font-black mb-2 lg:mb-4">section.opening.title</h1>
      <!--desc-->
      <p i18n="@@section.opening.desc" [ngClass]="!index ? 'text-white' : 'text-gray-700'" class="mb-2 lg:mb-4">section.opening.desc</p>
      <p i18n="@@section.opening.desc2" [ngClass]="!index ? 'text-white' : 'text-gray-700'" class="mb-2 lg:mb-4">section.opening.desc2</p>
      <p i18n="@@section.opening.target" [ngClass]="!index ? 'text-white' : 'text-gray-700'">section.opening.target</p>
    </div>
  </div>
</div>
