// packages/vue/src/pages/home/index.vue
<script lang="ts" setup>
import type { ElementPositionProgress } from '@about-me-mix/common'
import { getElementProgressData, getChildrenRect } from '@about-me-mix/common'
import { useWebsite } from '@/stores'
import { useProgress } from '@/stores/progress'
import SectionOpening from '@/components/section/opening/index.vue'
import SectionDialogue from '@/components/section/dialogue/index.vue'
import SectionExperience from '@/components/section/experience/index.vue'
import SectionCoding from '@/components/section/coding/index.vue'
import SectionShader from '@/components/section/shader/index.vue'

// progress cache
const childrenProgressData = ref<ElementPositionProgress[]>([])

// 保存位置資訊位置
const onScrollHandler = () => useProgress().setSectionProgress(getElementProgressData(childrenProgressData.value))
onBeforeMount(() => window.addEventListener('scroll', onScrollHandler))
onUnmounted(() => window.removeEventListener('scroll', onScrollHandler))

// on resize
const sizeUpdateTimestamp = computed(() => useWebsite().sizeUpdateTimestamp)
watch(sizeUpdateTimestamp, onScrollHandler)

// 快取子層位置，避免一直計算
const main = ref<HTMLElement>()
watch([main], () => {
  if (!main.value) return
  childrenProgressData.value = getChildrenRect(main.value)
  onScrollHandler()
})

const section = [SectionOpening, SectionDialogue, SectionExperience, SectionCoding, SectionShader]
</script>

<template>
  <main ref="main">
    <Component v-for="(component, index) in section" :is="component" :key="index" :index="index" />
  </main>
</template>

// packages/svelte/src/routes/[locale]/home/+page.svelte
<script lang="ts">
  import type { ElementPositionProgress } from '@about-me-mix/common'
  import { getChildrenRect, getElementProgressData } from '@about-me-mix/common'
  import { sizeUpdateTimestamp } from '@/stores'
  import { onDestroy, onMount } from 'svelte'
  import { browser } from '$app/environment'
  import SectionOpening from '@/components/section/opening/index.svelte'
  import SectionDialogue from '@/components/section/dialogue/index.svelte'
  import SectionExperience from '@/components/section/experience/index.svelte'
  import SectionCoding from '@/components/section/coding/index.svelte'
  import SectionShader from '@/components/section/shader/index.svelte'
  import { setSectionProgress } from '@/stores/progress'

  // progress cache
  let childrenProgressData: ElementPositionProgress[] = []

  // 保存位置資訊位置
  const onScrollHandler = () => setSectionProgress(getElementProgressData(childrenProgressData))
  onMount(() => browser && window.addEventListener('scroll', onScrollHandler))
  onDestroy(() => browser && window.removeEventListener('scroll', onScrollHandler))
  $: if ($sizeUpdateTimestamp) onScrollHandler()

  // 快取子層位置，避免一直計算
  let main: HTMLElement
  $: if (main) {
    childrenProgressData = getChildrenRect(main)
    onScrollHandler()
  }

  // section
  const section = [SectionOpening, SectionDialogue, SectionExperience, SectionCoding, SectionShader]
</script>

<!--Home Page-->
<main bind:this={main}>
  {#each section as Component, index (index)}
    <svelte:component this={Component} {index} />
  {/each}
</main>
