// projects/svelte-kit2/src/components/home/components/shader/index.svelte
<script lang="ts">
  import { createShaderTween, type TweenShader } from '@about-me-mix/communal/src/shader'
  import { state } from '../../../../stores/initialize'
  import { t } from '$lib/i18n'
  import useProgress from '../../hook/use-progress'
  import { MIX_ASSETS_URL } from '$env/static/public'

  // progress data
  export let index = 0
  let progress = useProgress(index)

  const initialize = (container: HTMLDivElement) => {
    // update shadow params
    let shader: TweenShader

    createShaderTween(container?.querySelector('canvas'), {
      bg: '#27272a',
      bg2: '#e11d48',
      noise: `${MIX_ASSETS_URL}/noise.jpg`,
      noise2: `${MIX_ASSETS_URL}/noise2.jpg`,
    }).then(tween => {
      shader?.kill()
      shader = tween
      shader.progress($progress?.progress || 0)
    })

    // on resize
    let prevSizeUpdateTimestamp = 0
    const unSubscribe = state.subscribe(({ sizeUpdateTimestamp }) => {
      if (prevSizeUpdateTimestamp === sizeUpdateTimestamp) return
      prevSizeUpdateTimestamp = sizeUpdateTimestamp
      shader?.resetSize()
    })

    return {
      // on progress update
      update({ hidden, progress }) {
        if (hidden) return
        shader?.progress(progress)
      },
      destroy() {
        shader?.kill()
        unSubscribe()
      },
    }
  }
</script>

<section class="h-300vh">
  <div use:initialize={$progress} style:display={$progress?.hidden ? 'none' : ''} class="h-full">
    <canvas class="h-100vh w-full sticky top-0 z-10" />
    <div class="h-100vh" />
    <div class="w-full h-100vh relative z-0 flex items-center justify-center font-bold text-white text-10 lg:text-16">
      {$t('thank')}
    </div>
  </div>
</section>

// projects/nuxt3/src/components/home/components/shader/index.vue
<script lang="ts" setup>
import { createShaderTween, type TweenShader } from '@about-me-mix/communal/src/shader'
import { useClientStore } from '@/stores/initialize'
import useProgress from '../../hook/use-progress'

const { locale } = useI18n()
const props = defineProps({ index: { default: 0 } })
const { MIX_ASSETS_URL } = useRuntimeConfig().public

// update shadow params
const shader = ref<TweenShader>()
const container = ref<HTMLDivElement>()
onMounted(async () => {
  const canvas = container.value?.querySelector('canvas')
  if (!canvas) return
  shader.value = await createShaderTween(canvas, {
    bg: '#27272a',
    bg2: '#059669',
    noise: `${MIX_ASSETS_URL}/noise.jpg`,
    noise2: `${MIX_ASSETS_URL}/noise2.jpg`,
  })
  shader.value?.progress(position.value?.progress || 0)
})
onBeforeUnmount(() => shader.value?.kill())

// on resize
const sizeUpdateTimestamp = computed(() => useClientStore().sizeUpdateTimestamp)
watch(sizeUpdateTimestamp, () => shader.value?.resetSize())

// on position update
const { position } = useProgress(props.index, ({ height, hidden, progress }) => {
  if (height === 0) return
  // hidden
  if (container.value) container.value.style.display = hidden ? 'none' : ''
  // update tween
  if (!hidden) shader.value?.progress(progress)
})
</script>

<template>
  <section class="h-300vh">
    <div v-once ref="container" class="h-full">
      <canvas class="h-100vh w-full sticky top-0 z-10" />
      <div class="h-100vh" />
      <div class="w-full h-100vh relative z-0 flex items-center justify-center font-bold text-white text-10 lg:text-16" v-t="'thank'" />
    </div>
  </section>
</template>
